// a=document.images[0];
// console.log(a);
// a=document.images[1];
// console.log(a);
// a=document.scripts[0];
// console.log(a)var;
var name = "harry";
var channel;
var marks = 3454;

var city = "delhi"
const arr1 = [1,2,3,4,5,6]
arr1.push(74);
// WE CAN NOT ASSIGN AN CONSTANT ARR
console.log(arr1);
console,log("my name is "+name)
 let marks = {harry : 89,
subham:36,
rohan das: 55 }
console.log(typeof marks)
let element = document.getElementById("mikuns");
console,log(element);